[xdebug]
; Xdebug configuration for development

xdebug.mode = debug,coverage,profile
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.log = /var/log/xdebug.log
xdebug.log_level = 0

; Profiling
xdebug.output_dir = /var/www/html/storage/logs/xdebug
xdebug.profiler_output_name = cachegrind.out.%t-%s

; Coverage
xdebug.coverage_enable = 1
